<?php

namespace AppBundle\Repository;

/**
 * MessageUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageUsersRepository extends \Doctrine\ORM\EntityRepository
{
}
