<?php

namespace AppBundle\Repository;

/**
 * UserLikingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLikingRepository extends \Doctrine\ORM\EntityRepository
{
}
